### ISSUE TITLE
Typo in Dockerfile

### ISSUE THREAD

**Issue by SchoolyB** [PlummersSoftwareLLC/Odin-docker#1]
First line of Dockerfile says

`ROM ubuntu:20.04`
 
Should be `FROM ubuntu:20.04`

**Comment by rbergen** [comment]
That's a very eagle-eyed catch. I already fixed this last February as part of a version bump of Ubuntu and Odin, but neglected to push the commit. That has now been fixed in commit https://github.com/PlummersSoftwareLLC/Odin-docker/commit/efa168d28c918a878da316dd67baecaf37ded813.
